### ISSUE TITLE
[lang] Add JavaScript

### ISSUE THREAD

**Issue by amino19** [devstrons/heloworld.xyz#73]
#### Current Behavior

This project doesn't have `JavaScript` language, not even in the pull request I find something relates fs!

#### Desired Behavior

`JavaScript` language must be consider inside `lang` folder.

#### Implementation

The way of implementation listed on README.md, section consisting [contribution guidelines](https://github.com/devstrons/heloworld.xyz#%EF%B8%8F-contribution-guidelines). 

---
#### Contributor Guides and Resources
- 🛠 [Reference for building](https://github.com/devstrons/heloworld.xyz/blob/main/lang/java.md)
- 📚 [Instructions for contributing to documentation](https://github.com/devstrons/heloworld.xyz#%EF%B8%8F-contribution-guidelines)
- :exclamation: [Code of Conduct](https://github.com/devstrons/heloworld.xyz/blob/main/CODE_OF_CONDUCT.md)
- 🙋🏾🙋🏼 Questions: [Discord discussion server](https://discord.gg/invite/MVujzTBqed)

**Comment by umng01** [comment]
Thanks for this, happy to be a part of the same!
Super excited!! I'll be starting by today :)
