### ISSUE TITLE
[lang] Add Golang

### ISSUE THREAD

**Issue by amino19** [devstrons/heloworld.xyz#74]
#### Current Behavior

This project doesn't have `Go` language, not even in the pull request I find something relates fs!

#### Desired Behavior

`Go` language must be considered inside the `lang` folder.

#### Implementation

The way of implementation listed on README.md, section consisting [contribution guidelines](https://github.com/devstrons/heloworld.xyz#%EF%B8%8F-contribution-guidelines). 

---
#### Contributor Guides and Resources
- 🛠 [Reference for building](https://github.com/devstrons/heloworld.xyz/blob/main/lang/java.md)
- 📚 [Instructions for contributing to documentation](https://github.com/devstrons/heloworld.xyz#%EF%B8%8F-contribution-guidelines)
- :exclamation: [Code of Conduct](https://github.com/devstrons/heloworld.xyz/blob/main/CODE_OF_CONDUCT.md)
- 🙋🏾🙋🏼 Questions: [Discord discussion server](https://discord.gg/invite/MVujzTBqed)

**Comment by krishguptadev** [comment]
@amino19 you still working on this?

**Comment by amino19** [comment]
> @amino19 you still working on this?

No, actually a bit occupied nowadays. 
But, if you wanna take this up, pl step forward.

@ghulamyazdani will assign you for sure!
