### ISSUE TITLE
[lang] Add Bash

### ISSUE THREAD

**Issue by amino19** [devstrons/heloworld.xyz#77]
#### Current Behavior

This project doesn't have `Bash` language, not even in the pull request I find something relates fs!

#### Desired Behavior

`Bash` language must be considered inside the `lang` folder.

#### Implementation

The way of implementation listed on README.md, section consisting [contribution guidelines](https://github.com/devstrons/heloworld.xyz#%EF%B8%8F-contribution-guidelines). 

---
#### Contributor Guides and Resources
- 🛠 [Reference for building](https://github.com/devstrons/heloworld.xyz/blob/main/lang/java.md)
- 📚 [Instructions for contributing to documentation](https://github.com/devstrons/heloworld.xyz#%EF%B8%8F-contribution-guidelines)
- :exclamation: [Code of Conduct](https://github.com/devstrons/heloworld.xyz/blob/main/CODE_OF_CONDUCT.md)
- 🙋🏾🙋🏼 Questions: [Discord discussion server](https://discord.gg/invite/MVujzTBqed)

**Comment by tusqasi** [comment]
I would like to take this up.
#72

**Comment by krishguptadev** [comment]
@tusqasi you still working on this?

**Comment by tusqasi** [comment]
> @tusqasi you still working on this?

@krishguptadev not actively, if you want to add/change anything go ahead.

**Comment by amino19** [comment]
@krishguptadev: Sorry for the inconvenience caused, it's need to be close now! 

Thanks @tusqasi for your valuable contribution! 

@ghulamyazdani: Feel free to close this issue!
