### ISSUE TITLE
[lang] Add Julia

### ISSUE THREAD

**Issue by yashvardhan-verma** [devstrons/heloworld.xyz#83]
### Is your feature request related to a problem? Please describe.

This project doesn't have `Julia` language, not even in the pull request I find something that relates to fs!

### Describe the solution you'd like

I love like to add `Julia` language.

**Comment by Shivansh-yadav13** [comment]
Anyone working on this ?

**Comment by Panquesito7** [comment]
> Anyone working on this ?

Looks like not. Feel free to work on it. 🙂

**Comment by Shivansh-yadav13** [comment]
> > Anyone working on this ?
> 
> Looks like not. Feel free to work on it. 🙂

😁👍‍
